config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  get 'message/indexm'
  get '/like/indexlike/:id',to: "like#index_like"
  get "/like/liked_by/:id",to: "like#liked_by"
  
  namespace :admin do
    get 'users/index'
    get 'home/indexadmin'
    resources :home
    resources :users
  end
  get "/user/like/indexlike/:id",to: "like#index_like"
  get "/admin/home/indexadmin" ,to: "home#indexadmin"
  get "/admin/users/index", to: "users#index"
  get "/admin/friend/index", to: "friend#index"
   
  get "/message/create/:id",to: "message#create"
  get "/message/destroy/:id",to: "message#destroy"
  get "like/liked_by/profile/user_profile/:id", to:"profile#user_profile"
  get "message/indexm", to:"message#indexm"
  get "message/friend_message/:id",to: "message#friend_message" ,as: "friend_message"
  post "message/create_message"


  get 'reply/indexr'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root "post#index"
  
  get 'profile/index'
  get "profile/user_profile/:id", to:"profile#user_profile"
  get "/friendlist/profile/user_profile/:id", to:"profile#user_profile"
  get "/indexp", to:"profile#indexp"
  
  get "/index", to:"post#index"
  resources :post
  
  get '/indexf' , to:"friendlist#indexf"
  get "/create/:id", to: "friendlist#create"
  get "friendlist/friend", to: "friendlist#friend"
  get 'friendlist/indexf'
  get "user/friend",to: "profile#user_post"
  get "/friendlist/friendrequest",to: "friendlist#friend_request" 
  get "/friendlist/update/:id",to:"friendlist#update"
  delete "/friendlist/destroy/:id",to:"friendlist#destroy"

  get "/replies" ,to: "reply#indexr"
  get 'comment/index/:id', to: 'comment#index',as: "comment_index"
  get 'comment/index/:id', to: 'comment#index'
  get "reply/new/:id", to:"reply#new"
  get "/replies/:id",to: "reply#indexr"
  resources :comment
  resources :reply
  resources :friendlist
  resources :message
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  has_many :replies, class_name: "Comment",foreign_key: "coment_id",dependent: :delete_all
  belongs_to :coment, class_name: "Comment", optional: true
  
  
  # after_save :comments
  # private
  # def comments
  #   if text == ""
  #     Comment.last.delete
  #   end
  # end
  
  
  # before_destroy :comment
  # private
  # def comment
  #   if text == "anu"
  #     Comment.create(text:"anupam",userid:userid,post_id:post_id)
  #   end
  # end 
  
end

app/models/friendlist.rb
class Friendlist < ApplicationRecord
    has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to:post
    belongs_to:user
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user 
  has_many :comments,dependent: :delete_all
  has_many :likes
  mount_uploader :image, CoverUploader
  # scope :posts, ->{where(text: "Jindagi mast ")}
  # scope :postsid, ->{where(id:42)}
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :restaurant_type, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
      # before_validation :login, :email, presence: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :posts ,dependent: :destroy

  mount_uploader :image, CoverUploader
  def self.from_google(email:, full_name:, uid:, avatar_url:)
    user = create_with( name: full_name, image: avatar_url, password: 12345678).find_or_create_by!(email: email)
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
    @users=User.all
    @comments=Comment.all
    @postcomments = Post.find(params[:id]).comments
    @replies=Array.new
    i=0
    j=1
    @comments.each do|comment| 
      if comment.coment_id != nil
        while (i<j)
          @replies[i] = comment
          i+=1
        end
        j+=1
      end
    end
    $postid=Post.find(params[:id])
    @commentcount=commentcount()
  end
  
  def create
    @comments = Comment.new(text:params["title"],post_id:$postid.id,userid:current_user.id)
    if @comments.save
      redirect_to comment_index_path($postid.id)
    else
      render :new
    end
  end
  
  def edit
    @comments = Comment.find(params[:id])
  end

  def update
    @comments = Comment.find(params[:id])
    @comments.update(text:params["text"])
      if @comments.save  
        redirect_to root_url
      else
        render :edit
      end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to comment_index_path($postid.id)
  end

  def commentcount
    sum=0
    @postcomments.each do |i|
      if i.coment_id == nil
        sum+=1
      end
    end
    return sum
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[current_user.id])
  end

  def update
    @user = User.find(params[:id])
    if @posts.update()
      redirect_to @posts
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def index_like
    vari = Post.find(params[:id])
    @likes = Like.new(post_id:vari.id,user_id:current_user.id)
    if !(Like.find_by(user_id: current_user.id, post_id:vari.id))
      if current_user != vari.user
        if @likes.save
          flash[:success]='Post liked successfully'
          redirect_to post_index_path(vari)
        end
      else
        flash[:warning]="You can't like your post"
        redirect_to user_friend_path(vari)
      end
    else
      flash[:danger]='Post Unliked successfully'
      @dest = Like.find_by(user_id:current_user.id,post_id:params[:id])
      @dest.destroy
      redirect_to post_index_path(vari)
    end
  end

  def liked_by
    @liked_by = Post.find(params[:id]).likes
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :post_find ,only: [:edit,:update,:destroy]

  def index
    case 
    when current_user.user_type=="user"     
      post =Post.order(created_at: :desc) 
      current_user_posts=current_user.posts
      posts = post-current_user_posts
      @posts = posts.shuffle
    when current_user.user_type=="admin"
      redirect_to "/admin/home/indexadmin"
    end
  end

  def new 
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    redirect_to indexp_url
  end

  def edit
  end

  def update
    @post.update(text:params["text"])
    if @post.save  
      redirect_to indexp_url
    end
  end

  def destroy
    @post.destroy
    redirect_to user_friend_path
  end  

  private
  
  def post_find
      @post = Post.find(params[:id])
  end

  def post_params
    params.permit(:text, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/friendlist_helper.rb
module FriendlistHelper
end

app/helpers/harshit_helper.rb
module HarshitHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/post_helper.rb
module PostHelper
    # def format_name(post)
    #     post.each do |i|
    #         if i.text=="It is"
    #             Post.find(i.id).update(text:"it")
    #         end
    #     end
    # end
end

app/helpers/profile_helper.rb
module ProfileHelper

end

app/helpers/reply_helper.rb
module ReplyHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/comment/edit.html.erb
<div class="container">
  <h1>Edit Your comment</h1>
  <%= form_with(url: comment_path(@comments), method: :patch) do |form| %>
    <div class="form-outline mb-4">
      <%= form.label :text %><br>
      <%= form.text_field :text  ,class: "form-control " %>
    </div>
    <div>
      <%= form.submit :save,class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/comment/index.html.erb
<h3 class="card-title text-center mt-3 mb-1">Total number of comments on this post : <%=@commentcount%></h3><br>

<h2 class="card-title text-center">All Comments</h2>
<%@postcomments.each do|postcomment|%>
    <%if postcomment.coment_id==nil%>
        <div class="comment-thread">
            <details open class="comment" id="comment-1">
                <a href="#comment-1" class="comment-border-link">
                    <span class="sr-only">Jump to comment-1</span>
                </a>
                <summary>
                    <div class="comment-heading">
                        <div class="comment-voting">
                            <button type="button">
                                <span aria-hidden="true">&#9650;</span>
                                <span class="sr-only">Vote up</span>
                            </button>
                            <button type="button">
                                <span aria-hidden="true">&#9660;</span>
                                <span class="sr-only">Vote down</span>
                            </button>
                        </div>
                        <% if User.find(postcomment.userid).image_url %>
                            <img src="<%=User.find(postcomment.userid).image_url %>" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 " style="width: 40px; z-index: 1">
                        <%else%>
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 40px; z-index: 1">
                        <%end%>
                        <div class="comment-info">
                            <a href="#" class="comment-author"><%=User.find(postcomment.userid).name%></a>
                            <p class="m-0">
                                <%=postcomment.created_at%>
                            </p>
                        </div>
                    </div>
                </summary>
                <div class="comment-body mt-2">
                <div class="m-b-15 d-block font-medium", style="font-family:sans-serif;font-size:1.8em;">
                    <h5>
                    <%=postcomment.text%>
                    </h5>
                    </div>
                        <button type="button" class="btn btn-cyan btn-sm"><a href="/reply/new/<%=postcomment.id%>">Reply</a></button><br>
                        <% if postcomment.userid == current_user.id %>
                            <%=link_to 'Edit', edit_comment_path(postcomment.id),class:"btn btn-success"%>
                            <%=link_to 'Delete',comment_path(postcomment.id), method: "delete",data:{confirm: "Are you sure ?"},class:"btn btn-danger"%></td>
                        <%end%>
                    <form method="POST" class="reply-form d-none" id="comment-1-reply-form">
                        <textarea placeholder="Reply to comment" rows="4"></textarea>
                        <button type="submit">Submit</button>
                        <button type="button" data-toggle="reply-form" data-target="comment-1-reply-form">Cancel</button>
                    </form>
                </div>

                <%@replies.each do|reply|%>
                    <% if reply.coment_id == postcomment.id%>
                        <div class="replies">
                            <details open class="comment" id="comment-2">
                                <a href="#comment-2" class="comment-border-link">
                                    <span class="sr-only">Jump to comment-2</span>
                                </a>
                                <summary>
                                <% if User.find(reply.userid).image_url %>
                                    <img src="<%=User.find(reply.userid).image_url %>" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 40px; z-index: 1">
                                <%else%>
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 40px; z-index: 1">
                                <%end%>
                                    <div class="comment-heading">                                
                                        <div class="comment-info">
                                            <a href="#" class="comment-author"><%=User.find(reply.userid).name%></a>
                                            <p class="m-0">
                                            <%=reply.created_at%>
                                            </p>
                                        </div>
                                    </div>
                                </summary>
                                <div class="comment-body">
                                    <h6>
                                        <%=reply.text%>                   
                                    </h6>
                                        <button type="button" class="btn btn-cyan btn-sm"><a href="/reply/new/<%=reply.id%>">Reply</a></button>
                                        <button type="button" class="btn btn-cyan btn-sm"><a href="/replies/<%=reply.id%>">Replies</a></button><br>
                                        <% if reply.userid == current_user.id %>
                                            <%=link_to 'Edit', edit_comment_path(reply.id),class:"btn btn-success"%>
                                            <%=link_to 'Delete',comment_path(reply.id), method: "delete",data:{confirm: "Are you sure ?"},class:"btn btn-danger"%></td>
                                        <%end%>
                                    <form method="POST" class="reply-form d-none" id="comment-2-reply-form">
                                        <textarea placeholder="Reply to comment" rows="4"></textarea>
                                        <button type="submit">Submit</button>
                                        <button type="button" data-toggle="reply-form" data-target="comment-2-reply-form">Cancel</button>
                                    </form>
                                </div>
                            </details>
                        </div>
                    <%end%>
                <%end%>
            </details>
        </div>
    <%end%>
<%end%>

<div style="justify-content: center; display: flex;">
  <div class="col-md-8 col-lg-6" style="padding-bottom: 50px; width: 37%;">
    <div class="card shadow-0 border" style="background-color: #f0f2f5;">
      <div class="card-body p-4">
        <div class="form-outline mb-4">
            <p> Type Message</p>
            <%= form_with(url: "/comment", method: :comments) do |form| %>
                <%= form.text_field :title %>
                <%= form.submit %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>