config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  get 'message/indexm'
  get '/like/indexlike/:id',to: "like#index_like"
  get "/like/liked_by/:id",to: "like#liked_by"
  
  namespace :admin do
    get 'users/index'
    get 'home/indexadmin'
    resources :home
    resources :users
  end
  get "/user/like/indexlike/:id",to: "like#index_like"
  get "/admin/home/indexadmin" ,to: "home#indexadmin"
  get "/admin/users/index", to: "users#index"
  get "/admin/friend/index", to: "friend#index"
   
  get "/message/create/:id",to: "message#create"
  get "/message/destroy/:id",to: "message#destroy"
  get "like/liked_by/profile/user_profile/:id", to:"profile#user_profile"
  get "message/indexm", to:"message#indexm"
  get "message/friend_message/:id",to: "message#friend_message" ,as: "friend_message"
  post "message/create_message"


  get 'reply/indexr'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root "post#index"
  
  get 'profile/index'
  get "profile/user_profile/:id", to:"profile#user_profile"
  get "/friendlist/profile/user_profile/:id", to:"profile#user_profile"
  get "/indexp", to:"profile#indexp"
  
  get "/index", to:"post#index"
  resources :post
  
  get '/indexf' , to:"friendlist#indexf"
  get "/create/:id", to: "friendlist#create"
  get "friendlist/friend", to: "friendlist#friend"
  get 'friendlist/indexf'
  get "user/friend",to: "profile#user_post"
  get "/friendlist/friendrequest",to: "friendlist#friend_request" 
  get "/friendlist/update/:id",to:"friendlist#update"
  delete "/friendlist/destroy/:id",to:"friendlist#destroy"

  get "/replies" ,to: "reply#indexr"
  get 'comment/index/:id', to: 'comment#index',as: "comment_index"
  get 'comment/index/:id', to: 'comment#index'
  get "reply/new/:id", to:"reply#new"
  get "/replies/:id",to: "reply#indexr"
  resources :comment
  resources :reply
  resources :friendlist
  resources :message
end

app/models/friendlist.rb
class Friendlist < ApplicationRecord
    has_many :users
end

app/controllers/friendlist_controller.rb
class FriendlistController  < ApplicationController
  def indexf
    userid = Array.new
    user = Array.new
    user = User.all
    j=0
    k=1
    user.each do |i|
      if i.user_type != "admin"
        if i.id != current_user.id 
          while(j<k)
            userid[j] = i.id
            j+=1      
          end
          k+=1
        end
      end
    end
    @pending = Array.new
    friends = Array.new
    friendlist=Array.new
    friendlist=Friendlist.all
    j=0
    k=1
    m=0
    n=1
    friendlist.each do |l|
      if l.current_user_id == current_user.id
        if l.friendship_status == "f"
          while(m<n)
            @pending[m] = l.friends_id
            m+=1
          end
          n+=1
        end
        while(j<k)
          friends[j] = l.friends_id
          j+=1
        end
        k+=1
      end
    end
    @users = userid - friends
  end
   
  def create
    user = User.find(params[:id])
    @friendlist = Friendlist.new(current_user_id: current_user.id, friends_id: user.id, friendship_status: false)
    if !(Friendlist.find_by(current_user_id: current_user.id, friends_id:user.id, friendship_status: false))
      if current_user.id != user.id
        if @friendlist.save
          flash[:success]='Friend request send successfully'
          redirect_to '/indexf'
        else
        render :new
        end
      else
        flash[:warning]="You can't like your post"
        redirect_to '/indexf'
      end
    else
      flash[:danger]='Friend request send successfully'
      redirect_to '/indexf'      
    end
  end

  def friend_request
    @friendrequest = Array.new
    @friendlist = Friendlist.all
    
    j=0
    k=1
    @friendlist.each do |i|
      if i.friends_id == current_user.id
        if i.friendship_status == "f"
          while(j<k)
            @friendrequest[j]=i
            j+=1
          end
          k+=1
        end
      end
    end
  end

  def update
    if params[:id]
      Friendlist.find(params[:id]).update_attribute(:friendship_status, true)
      Friendlist.create(current_user_id:current_user.id,friends_id:Friendlist.find(params[:id]).current_user_id,friendship_status: true)
      flash[:success] = 'Friendship request accepted'
      redirect_to "/indexp"
    else
      flash[:danger] = 'Friendship request not accepted'
      redirect_to '/indexf'
    end
  end

  def destroy
    if params[:id]
      Friendlist.find(params[:id]).delete
      flash[:success] = 'Friend request canceled or Friend removed'
      if params[:type] == "already"
        redirect_to friendlist_friend_path
      elsif params[:type] == "request"
        redirect_to friendlist_friendrequest_path
      else
        redirect_to '/indexf'
      end
    else
      flash[:danger] = 'Friendship request NOT canceled'
    end
  end

  def friend
    @friendlist=Friendlist.all
    @users=User.all
  end
end

app/helpers/friendlist_helper.rb
module FriendlistHelper
end

app/views/friendlist/friend.html.erb
<h2 style="border-radius: 20px; margin: 30px; background-color: black; padding: 20px; text-align: center; color: white;"> Friends </h2>
<%@friendlist.each do|pending|%>
	<%if pending.current_user_id == current_user.id%>
		<%if pending.friendship_status != "f" %> 
			<div class="row" style="justify-content: center;">
				<div class="col-md-8">
					<div class="people-nearby">   
						<div class="nearby-user">
						<div class="row" style="align-items: center;">
							<div class="col-md-2 col-sm-2">
							<a style="text-decoration:none;" href="profile/userprofile/<%=pending.friends_id%>">
								<% if User.find(pending.friends_id).image_url%>
									<img src="<%=User.find(pending.friends_id).image.url%>" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 round rounded-circle" style="width: 100px; z-index: 1">
								<%else%>
									<img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 round rounded-circle" style="width: 100px; z-index: 1">  
								<%end%>	 
							</a>	                    
							</div>
							<div class="col-md-7 col-sm-7">
								<h5><a href="profile/user_profile/<%=pending.friends_id%>" class="profile-link" style="text-decoration:none; color:black;" ><%=User.find(pending.friends_id).name%></a></h5>
								<p><%=User.find(pending.friends_id).location%></p>
							</div>
							<div class="col-md-3 col-sm-3 ">
							<%=button_to 'Remove Friend', friendlist_path(pending.id, type: "already"),class:"btn btn-danger pull-right mb-2",method: :delete%>	
							</div>
						</div>
						</div>
					</div>
				</div>
			</div>
		<%end%>
	<%end%>	
<%end%>

app/views/friendlist/friend_request.html.erb
 <% flash.each do |type,msg| %>
    <div class="alert alert-success">
      <%=msg %>
    </div>
    <% end %>


<%@friendrequest.each do|request|%>

			<div class="row" style="justify-content: center;">
				<div class="col-md-8">
					<div class="people-nearby">   
						<div class="nearby-user">
						<div class="row" style="align-items: center;">
							<div class="col-md-2 col-sm-2">
                      <% if User.find(request.current_user_id).image_url%>
                        <img src="<%=User.find(request.current_user_id).image.url%>" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">
                      <%else%>
                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">
                      <%end%>
                    </div>
                    <div class="col-md-7 col-sm-7">
                      <h5><a href="profile/user_profile/<%=request.current_user_id%>" class="profile-link" style="text-decoration:none; ,text-white" ><%=User.find(request.current_user_id).name%></a></h5>
                      <p><%=User.find(request.current_user_id).location%></p>
                    </div>
                    <div class="col-md-3 col-sm-3 ">
                      <a href="/friendlist/update/<%=request.id%>" role="button" class="btn btn-success pull-right mb-3">Accept Request</a>
                    <%=button_to 'Decline Request', friendlist_path(request.id, type: "request"),class:"btn btn-danger pull-right mb-2",method: :delete%>	

                    </div>
						</div>
						</div>
					</div>
				</div>
			</div>

<%end%>

app/views/friendlist/indexf.html.erb
 <% flash.each do |type,msg| %>
    <div class="alert alert-success">
      <%=msg %>
    </div>
    <% end %>
<% if @pending != []%>
  <div class="container mt-3">
    <h4 style="    border-radius: 20px;
    color: white;
    background-color: black;
    text-align: center;
    padding: 50px;">Already Send requests</h4>
    <%@pending.each do|pending|%>
      <div class="row" style="justify-content: center;">
        <div class="col-md-8">
            <div class="people-nearby">   
              <div class="nearby-user">
                <div class="row" style="align-items: center;">
                  <div class="col-md-2 col-sm-2">
                    <a style="text-decoration:none;" href="profile/userprofile/<%=pending%>">
                      <% if User.find(pending).image_url%>
                        <img src="<%=User.find(pending).image.url%>" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 round rounded-circle" style="width: 100px; z-index: 1">
                      <%else%>
                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 round rounded-circle" style="width: 100px; z-index: 1">  
                      <%end%>	 
                    </a>	                    
                  </div>
                  <div class="col-md-7 col-sm-7">
                    <h5><a href="profile/user_profile/<%=pending%>" class="profile-link" style="text-decoration:none; color:black;" ><%=User.find(pending).name%></a></h5>
                    <p><%=User.find(pending).location%></p>
                  </div>
                  <div class="col-md-3 col-sm-3 ">
                    <%=button_to 'Cancle Request', friendlist_path(Friendlist.find_by(friends_id:pending).id, type: "requests"),class:"btn btn-danger pull-right mb-3",method: :delete%>	
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    <%end%>
  </div>
<%end%>
  
<div class="container">
  <h4 style="    border-radius: 20px;
    color: white;
    background-color: black;
    text-align: center;
    padding: 50px;">New Users</h4>
  <%@users.each do|user|%>
    <div class="row" style="justify-content: center;">
      <div class="col-md-8">
        <div class="people-nearby">   
          <div class="nearby-user">
            <div class="row" style=" align-items: center;">
              <div class="col-md-2 col-sm-2">	
                <a style="text-decoration:none;" href="profile/userprofile/<%=user%>">
                  <% if User.find(user).image_url%>
                    <img src="<%=User.find(user).image_url%>" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 round rounded-circle" style="width: 100px; z-index: 1">
                  <%else%>
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 round rounded-circle" style="width: 100px; z-index: 1">
                  <%end%>	    
                </a>				
              </div>
              <div class="col-md-7 col-sm-7">
                <h5><a href="profile/user_profile/<%=user%>" class="profile-link" style="text-decoration:none; color:black;" ><i class="icon ion-md-time"></i><%= User.find(user).name%></a></h5>
                <p><%=User.find(user).location%></p>
              </div>
              <div class="col-md-3 col-sm-3 ">
                <a href="/create/<%=user%>" role="button" class="btn btn-success pull-right mb-3">Add Friend</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>