config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  get 'message/indexm'
  get '/like/indexlike/:id',to: "like#index_like"
  get "/like/liked_by/:id",to: "like#liked_by"
  
  namespace :admin do
    get 'users/index'
    get 'home/indexadmin'
    resources :home
    resources :users
  end
  get "/user/like/indexlike/:id",to: "like#index_like"
  get "/admin/home/indexadmin" ,to: "home#indexadmin"
  get "/admin/users/index", to: "users#index"
  get "/admin/friend/index", to: "friend#index"
   
  get "/message/create/:id",to: "message#create"
  get "/message/destroy/:id",to: "message#destroy"
  get "like/liked_by/profile/user_profile/:id", to:"profile#user_profile"
  get "message/indexm", to:"message#indexm"
  get "message/friend_message/:id",to: "message#friend_message" ,as: "friend_message"
  post "message/create_message"


  get 'reply/indexr'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root "post#index"
  
  get 'profile/index'
  get "profile/user_profile/:id", to:"profile#user_profile"
  get "/friendlist/profile/user_profile/:id", to:"profile#user_profile"
  get "/indexp", to:"profile#indexp"
  
  get "/index", to:"post#index"
  resources :post
  
  get '/indexf' , to:"friendlist#indexf"
  get "/create/:id", to: "friendlist#create"
  get "friendlist/friend", to: "friendlist#friend"
  get 'friendlist/indexf'
  get "user/friend",to: "profile#user_post"
  get "/friendlist/friendrequest",to: "friendlist#friend_request" 
  get "/friendlist/update/:id",to:"friendlist#update"
  delete "/friendlist/destroy/:id",to:"friendlist#destroy"

  get "/replies" ,to: "reply#indexr"
  get 'comment/index/:id', to: 'comment#index',as: "comment_index"
  get 'comment/index/:id', to: 'comment#index'
  get "reply/new/:id", to:"reply#new"
  get "/replies/:id",to: "reply#indexr"
  resources :comment
  resources :reply
  resources :friendlist
  resources :message
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  has_many :replies, class_name: "Comment",foreign_key: "coment_id",dependent: :delete_all
  belongs_to :coment, class_name: "Comment", optional: true
  
  
  # after_save :comments
  # private
  # def comments
  #   if text == ""
  #     Comment.last.delete
  #   end
  # end
  
  
  # before_destroy :comment
  # private
  # def comment
  #   if text == "anu"
  #     Comment.create(text:"anupam",userid:userid,post_id:post_id)
  #   end
  # end 
  
end

app/models/friendlist.rb
class Friendlist < ApplicationRecord
    has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to:post
    belongs_to:user
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user 
  has_many :comments,dependent: :delete_all
  has_many :likes
  mount_uploader :image, CoverUploader
  # scope :posts, ->{where(text: "Jindagi mast ")}
  # scope :postsid, ->{where(id:42)}
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :restaurant_type, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
      # before_validation :login, :email, presence: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :posts ,dependent: :destroy

  mount_uploader :image, CoverUploader
  def self.from_google(email:, full_name:, uid:, avatar_url:)
    user = create_with( name: full_name, image: avatar_url, password: 12345678).find_or_create_by!(email: email)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[current_user.id])
  end

  def update
    @user = User.find(params[:id])
    if @posts.update()
      redirect_to @posts
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def index_like
    vari = Post.find(params[:id])
    @likes = Like.new(post_id:vari.id,user_id:current_user.id)
    if !(Like.find_by(user_id: current_user.id, post_id:vari.id))
      if current_user != vari.user
        if @likes.save
          flash[:success]='Post liked successfully'
          redirect_to post_index_path(vari)
        end
      else
        flash[:warning]="You can't like your post"
        redirect_to user_friend_path(vari)
      end
    else
      flash[:danger]='Post Unliked successfully'
      @dest = Like.find_by(user_id:current_user.id,post_id:params[:id])
      @dest.destroy
      redirect_to post_index_path(vari)
    end
  end

  def liked_by
    @liked_by = Post.find(params[:id]).likes
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :post_find ,only: [:edit,:update,:destroy]

  def index
    case 
    when current_user.user_type=="user"     
      post =Post.order(created_at: :desc) 
      current_user_posts=current_user.posts
      posts = post-current_user_posts
      @posts = posts.shuffle
    when current_user.user_type=="admin"
      redirect_to "/admin/home/indexadmin"
    end
  end

  def new 
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    redirect_to indexp_url
  end

  def edit
  end

  def update
    @post.update(text:params["text"])
    if @post.save  
      redirect_to indexp_url
    end
  end

  def destroy
    @post.destroy
    redirect_to user_friend_path
  end  

  private
  
  def post_find
      @post = Post.find(params[:id])
  end

  def post_params
    params.permit(:text, :image)
  end
end

app/controllers/reply_controller.rb
class ReplyController < ApplicationController 

  def indexr
    @users=User.all
    comments=Comment.all
    @replies=Array.new
    i=0
    j=1
    comments.each do|comment| 
      if comment.coment_id != nil
        if comment.coment_id == params[:id].to_i
          while (i<j)
            @replies[i] = comment
            i+=1
          end
          j+=1
        end
      end
    end
    @repliescount=i
  end

  def new
    @replies = Comment.new
    $commentid=params[:id]
  end

  def create
    @replies = Comment.new(text:params["title"],post_id:$postid.id,userid:current_user.id,coment_id:$commentid)
    if @replies.save
      redirect_to comment_index_path($postid.id)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/friendlist_helper.rb
module FriendlistHelper
end

app/helpers/harshit_helper.rb
module HarshitHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/post_helper.rb
module PostHelper
    # def format_name(post)
    #     post.each do |i|
    #         if i.text=="It is"
    #             Post.find(i.id).update(text:"it")
    #         end
    #     end
    # end
end

app/helpers/profile_helper.rb
module ProfileHelper

end

app/helpers/reply_helper.rb
module ReplyHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/like/index_like.html.erb
<h4>Total no of likes on this post : <%=@likecount%></h4>

app/views/like/indexlike.html.erb
<h4>Total no of likes on this post : <%=@likecount%></h4>

app/views/like/liked_by.html.erb
<h1 style="padding: 25px; justify-content: center; display: flex;"> Liked By </h1>
<%@liked_by.each do|user|%>
  <div class="container">
    <div class="row" style="justify-content: center; ">
      <div class="col-md-8">
        <div class="people-nearby">   
          <div class="nearby-user">
            <div class="row" style="align-items: center;">
              <div class="col-md-2 col-sm-2">
                <% if User.find(user.user_id).image_url%>
                  <img src="<%=User.find(user.user_id).image.url%>" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">
                <%else%>
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">  
                <%end%>	                     
              </div>
              <div class="col-md-7 col-sm-7">
                <h5><a href="profile/user_profile/<%=user.user_id%>" class="profile-link" style="text-decoration:none; color:black;" ><%=User.find(user.user_id).name%></a></h5>
                <h6>
                <p><%=User.find(user.user_id).location%></p>
              </div>
              <div class="col-md-3 col-sm-3 ">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/post/_new.html.erb
<%= form_with(url: "/post", method: :post) do |form| %>
      <div class="modal-body">
            <%= form.text_field :text %><br>
         <p><%= form.label :Choose_Image %></p>
         <div class="formsix-pos">
            <div class="form-group i-email">
               <%= form.file_field :image %><br>
            </div>
         </div>
         <%# <%= form.file_field :image <br> %>
      </div>
      <div class="modal-footer">
            <%= form.submit "Upload"  %>
         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
<% end %>

app/views/post/edit.html.erb
<div class="container mt-4">
  <h1>Edit Your Post</h1>
  <%= form_with(url: post_path(@post), method: :patch) do |form| %>
    <div class="form-outline mb-4">
      <%= form.label :text %><br>
      <%= form.text_field :text  ,class: "form-control " %>
    </div>
    <div>
      <%= form.submit :save,class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/post/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<div class="container mb-3">
	<div class="col-lg-6 offset-lg-3 ">
		<h1 style="text-align:center;"> All Posts</h1>
	</div>
</div>
<% flash.each do |type,msg| %>
	<div class="alert alert-success">
		<%=msg %>
	</div>
<% end %>
<%@posts.each do |post|  %>
	<section class="hero">
    	<div class="container mb-3">
        	<div class="row">	
		   		<div class="col-lg-6 offset-lg-3">
					<div class="cardbox shadow-lg bg-white" style="max-height: 800px; border-radius: 30px; margin-bottom: 10px;">
			 			<div class="cardbox-heading">
			  				<div class="media m-0">
			   					<div class="mr-3 m-2" style="display: flex; border-top: none !important; border-width: 1px !important; border-right: none !important; border-left: none !important; border: solid; border-radius: 5px;">	
									<div>
									<a style="text-decoration:none;" href="profile/user_profile/<%=post.user.id%>">
                                    	<% if User.find(post.user_id).image_url%>
											<img src="<%=User.find(post.user_id).image_url%>" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 round rounded-circle" style="width: 60px; z-index: 1">
										<%else%>
											<img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 round rounded-circle" style="width: 80px; z-index: 1">
										<%end%>	    
									<span style="font-family:sans-serif;font-size:1em; text-decoration:none;"><i class="icon ion-md-time"></i><%=  post.user.name%></span>
									</a>
									</div>
									<div style="flex-grow: 5;"></div>
									<div style="flex-grow: 1;">
									<p style="font-family:sans-serif;font-size:12px; margin-left: 20% !important; margin-top: 46px; max-height: 10px;"><%=post.created_at.strftime('%d/%m/%Y')%></p>
								</div>
								</div>
			   					<div class="media-body m-2">
									<p style="font-family:sans-serif;font-size:1.2em;"><%=post.text%></p>
			 	  				</div>
			  				</div>
			 			</div>
			 			<div class="cardbox-item">
							<% if post.image_url%>
							<div style="justify-content: space-around;display: flex;">
						 		<%= image_tag(post.image.url,class:"img-fluid m-3", style:"max-width: 600px; max-height: 500px;")%>
     			        	</div>
							<%end%>
							<% @liked_by = Post.find(post.id).likes %>
							
							<div style="justify-content: space-around; display: flex; height: 30px;">
								<div style="colour: grey;" class="bi bi-hand-thumbs-up grey-icon">
								<% if @liked_by.present? %>
									<% counts = @liked_by.count%>
									<%if counts == 1%>
										<a href="profile/user_profile/<%=@liked_by.first.user_id%>" class="profile-link" style="text-decoration:none; color:grey;" ><%=User.find_by(id: @liked_by.first.user_id).name%></a>
									<%elsif counts == 2%>
										<p style="display: inline; colour: grey"><a href="profile/user_profile/<%=@liked_by.first.user_id%>" class="profile-link" style="text-decoration:none; color:grey;" ><%= User.find_by(id: @liked_by.first.user_id).name if @liked_by.present?%></a> and
										<a href="profile/user_profile/<%=@liked_by.second.user_id%>" class="profile-link" style="text-decoration:none; color:grey;" ><%= User.find_by(id: @liked_by.second.user_id).name if @liked_by.present?%></a></p>
									<%elsif counts > 2%>
										<p style="display: inline; colour: grey"><a href="profile/user_profile/<%=@liked_by.first.user_id%>" class="profile-link" style="text-decoration:none; color:grey;" ><%= User.find_by(id: @liked_by.first.user_id).name if @liked_by.present?%></a>,
										<a href="profile/user_profile/<%=@liked_by.second.user_id%>" class="profile-link" style="text-decoration:none; color:grey;" ><%= User.find_by(id: @liked_by.second.user_id).name if @liked_by.present?%></a> and <a style="text-decoration: none; color: #6c757d;" href="/like/liked_by/<%=post.id%>"><%=counts-2%> others</a></p>
									<%end%>
									<%else%>
										<p style="display: inline; colour: grey"><a> 0 likes</a></p>
									<%end%>
								</div>
								<div>
									<p style="display: inline;"> <%=post.comments.count%> <a href="comment/index/<%=post.id%> " style="color: grey;" class="bi bi-chat-dots"></a></p>
									</div>
								</div>
								
							<div class="alligning-container" style="height: 50px;">
								<div class=" m-2" style="max-width: 30%;">
									<%if Like.find_by(user_id:current_user.id,post_id:post.id)%>
										<h4><a href="like/indexlike/<%=post.id%>"><i class="bi bi-hand-thumbs-down m-5"></i> </a></h4>
									<%else%>
										<h4><a href="like/indexlike/<%=post.id%>"><i class="bi bi-hand-thumbs-up"></i> </a></h4>
									<%end%>
								</div>
								<div class="m-2" style="max-width: 30%;">
									<h4><a href="comment/index/<%=post.id%> "><i href="comment/index/<%=post.id%> " class="bi bi-chat-dots m-5" ></i></a></h4>
								</div>
							</div>
           				</div>	
						<br>
         			</div>
                </div>
			</div>
		</div>
    </section>
<%end%>

app/views/post/new.html.erb
<div class="row d-flex justify-content-center m-5">
  <div class="col-md-8 col-lg-6">
     <div class="card shadow-0 border" style="background-color: #f0f2f5;">
        <div class="card-body p-4">
          <div class="form-outline mb-4">
            <h1>Create new post</h1><br>
            <p>Enter Caption for your post<p>
            <%= form_with(url: "/post", method: :post) do |form| %>
               <%= form.text_field :text %><br>
               <p><%= form.label :Choose_Image %></p>
               <div class="formsix-pos">
                  <div class="form-group i-email">
                     <%= form.file_field :image %><br>
                  </div>
               </div>
               <%# <%= form.file_field :image <br> %>
               <div class="login_btn_wrapper">     
                  <%= form.submit "Upload" %>
               </div>
            <% end %>
          </div>
        </div>
     </div>
   </div>
</div>
<!--
<%= form_tag("/post", :method => "post") do %>
   <%= label_tag(:Upload_new_post) %><br>
   <%= text_field_tag(:text) %><br>
   <%= file_field_tag(:image) %><br>
   <%= submit_tag("Search") %>
<% end %>
-->

app/views/post/new.js.erb
$('#newPostForm').html('<%= escape_javascript render('new',post: @post)%>')