config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  get 'message/indexm'
  get '/like/indexlike/:id',to: "like#index_like"
  get "/like/liked_by/:id",to: "like#liked_by"
  
  namespace :admin do
    get 'users/index'
    get 'home/indexadmin'
    resources :home
    resources :users
  end
  get "/user/like/indexlike/:id",to: "like#index_like"
  get "/admin/home/indexadmin" ,to: "home#indexadmin"
  get "/admin/users/index", to: "users#index"
  get "/admin/friend/index", to: "friend#index"
   
  get "/message/create/:id",to: "message#create"
  get "/message/destroy/:id",to: "message#destroy"
  get "like/liked_by/profile/user_profile/:id", to:"profile#user_profile"
  get "message/indexm", to:"message#indexm"
  get "message/friend_message/:id",to: "message#friend_message" ,as: "friend_message"
  post "message/create_message"


  get 'reply/indexr'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root "post#index"
  
  get 'profile/index'
  get "profile/user_profile/:id", to:"profile#user_profile"
  get "/friendlist/profile/user_profile/:id", to:"profile#user_profile"
  get "/indexp", to:"profile#indexp"
  
  get "/index", to:"post#index"
  resources :post
  
  get '/indexf' , to:"friendlist#indexf"
  get "/create/:id", to: "friendlist#create"
  get "friendlist/friend", to: "friendlist#friend"
  get 'friendlist/indexf'
  get "user/friend",to: "profile#user_post"
  get "/friendlist/friendrequest",to: "friendlist#friend_request" 
  get "/friendlist/update/:id",to:"friendlist#update"
  delete "/friendlist/destroy/:id",to:"friendlist#destroy"

  get "/replies" ,to: "reply#indexr"
  get 'comment/index/:id', to: 'comment#index',as: "comment_index"
  get 'comment/index/:id', to: 'comment#index'
  get "reply/new/:id", to:"reply#new"
  get "/replies/:id",to: "reply#indexr"
  resources :comment
  resources :reply
  resources :friendlist
  resources :message
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  has_many :replies, class_name: "Comment",foreign_key: "coment_id",dependent: :delete_all
  belongs_to :coment, class_name: "Comment", optional: true
  
  
  # after_save :comments
  # private
  # def comments
  #   if text == ""
  #     Comment.last.delete
  #   end
  # end
  
  
  # before_destroy :comment
  # private
  # def comment
  #   if text == "anu"
  #     Comment.create(text:"anupam",userid:userid,post_id:post_id)
  #   end
  # end 
  
end

app/models/friendlist.rb
class Friendlist < ApplicationRecord
    has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to:post
    belongs_to:user
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user 
  has_many :comments,dependent: :delete_all
  has_many :likes
  mount_uploader :image, CoverUploader
  # scope :posts, ->{where(text: "Jindagi mast ")}
  # scope :postsid, ->{where(id:42)}
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :restaurant_type, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
      # before_validation :login, :email, presence: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :posts ,dependent: :destroy

  mount_uploader :image, CoverUploader
  def self.from_google(email:, full_name:, uid:, avatar_url:)
    user = create_with( name: full_name, image: avatar_url, password: 12345678).find_or_create_by!(email: email)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users=User.all
  end

  def userprofile
    @posts =Post.all
    @users=User.find(params[:id])
    @userpost = @users.posts
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to admin_users_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[current_user.id])
  end

  def update
    @user = User.find(params[:id])
    if @posts.update()
      redirect_to @posts
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def index_like
    vari = Post.find(params[:id])
    @likes = Like.new(post_id:vari.id,user_id:current_user.id)
    if !(Like.find_by(user_id: current_user.id, post_id:vari.id))
      if current_user != vari.user
        if @likes.save
          flash[:success]='Post liked successfully'
          redirect_to post_index_path(vari)
        end
      else
        flash[:warning]="You can't like your post"
        redirect_to user_friend_path(vari)
      end
    else
      flash[:danger]='Post Unliked successfully'
      @dest = Like.find_by(user_id:current_user.id,post_id:params[:id])
      @dest.destroy
      redirect_to post_index_path(vari)
    end
  end

  def liked_by
    @liked_by = Post.find(params[:id]).likes
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/friendlist_helper.rb
module FriendlistHelper
end

app/helpers/harshit_helper.rb
module HarshitHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/post_helper.rb
module PostHelper
    # def format_name(post)
    #     post.each do |i|
    #         if i.text=="It is"
    #             Post.find(i.id).update(text:"it")
    #         end
    #     end
    # end
end

app/helpers/profile_helper.rb
module ProfileHelper

end

app/helpers/reply_helper.rb
module ReplyHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/users/index.html.erb
<div class="container mt-3 mb-3">
	<div class="col-lg-6 offset-lg-0 ">
		<h1 style="text-align:center;"> All Users</h1>
	</div>
</div>
<%@users.each do|user|%>
      <div class="container">
          <div class="row">
              <div class="col-md-8">
                  <div class="people-nearby">   
                    <div class="nearby-user">
                      <div class="row">
                        <div class="col-md-2 col-sm-2">
                          <% if user.image_url%>
                            <img src="<%=user.image.url%>" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">
                          <%else%>
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">  
                          <%end%>	                     
                        </div>
                        <div class="col-md-7 col-sm-7">
                          <h5><a class="profile-link" style="text-decoration:none; color:black;" ><%=user.name%></a></h5>
                          <p><%=user.location%></p>
                        </div>
                        <div class="col-md-3 col-sm-3 ">
                            <h6><%= link_to 'Delete User' ,admin_user_path(user.id),method: :delete,class:"btn btn-danger pull-right mb-3",role:"button" %></h6>                    
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
        </div>
<%end%>

app/views/user/user.html.erb
<p><%= @users.email%></p>